<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="Description" content="Simon Biossac website, i'm 21, UI/UX designer, diplomate of sensory webdesign in Limoges, France. I'm passionate about streetwear, sneakers and minimalism art.">
<meta name='subject' content='Simon Biossac website'>
<meta name='author' content='Simon Biossac'>
<meta name="Publisher" content="Simon Biossac">
<meta name='Classification' content='Personnal'>
<meta name='copyright' content='Simon Biossac'>
<meta name='url' content='https://www.simonbiossac.fr'>
<meta name='date' content='Jan. 23, 2021'>
<meta name='language' content='FR'>
<meta name="keywords" lang="fr" content="Simon Biossac, UX designer, UX/UI designer, MMI Limoges, LPWS, webdesigner, ux design limoges, simonbiossac, simon, biossac">
<link rel="icon" type="image/png" href="https://build.simonbiossac.fr/assets/src/logo.png" />
